# Generated by Django 6.0.7 on 2026-07-26 18:13

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_quiz_quizquestion_quizchoice_and_more'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='LessonChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='catalog.course')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='catalog.lesson')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('lesson', 'order'), name='unique_chunk_order_per_lesson')],
            },
        ),
    ]
