# Generated by Django 6.0.7 on 2026-07-26 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lessonchunk',
            name='unique_chunk_order_per_lesson',
        ),
        migrations.DeleteModel(
            name='LessonChunk',
        ),
    ]
