# Generated by Django 6.0.7 on 2026-07-25 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeatLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_seats', models.PositiveIntegerField()),
                ('seats_used', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_licenses', to='orgs.organization')),
            ],
        ),
        migrations.CreateModel(
            name='SeatAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_assignments', to=settings.AUTH_USER_MODEL)),
                ('seat_license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='orgs.seatlicense')),
            ],
        ),
        migrations.AddConstraint(
            model_name='seatlicense',
            constraint=models.CheckConstraint(condition=models.Q(('seats_used__lte', models.F('total_seats'))), name='seats_used_not_over_total'),
        ),
        migrations.AddConstraint(
            model_name='seatassignment',
            constraint=models.UniqueConstraint(fields=('seat_license', 'user'), name='unique_user_per_license'),
        ),
    ]
