# Generated by Django 6.0.7 on 2026-07-26 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatassignment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seat_assignments', to='orders.order'),
        ),
        migrations.AddField(
            model_name='seatassignment',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
